// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKgtFVNsMbG5U4tIXmCd7g4pD04yBCIk',
    appId: '1:834378788334:web:93a60cb40fba6b78ddb2ff',
    messagingSenderId: '834378788334',
    projectId: 'locate-507c2',
    authDomain: 'locate-507c2.firebaseapp.com',
    storageBucket: 'locate-507c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspbgGLGEJAdVWFiGryeqoijb5yzHUrPc',
    appId: '1:834378788334:android:98cc011c7bab12f5ddb2ff',
    messagingSenderId: '834378788334',
    projectId: 'locate-507c2',
    storageBucket: 'locate-507c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZFvoTJX1npVRcpY36IQPxejH7lwWcQK4',
    appId: '1:834378788334:ios:399bf4e88b457101ddb2ff',
    messagingSenderId: '834378788334',
    projectId: 'locate-507c2',
    storageBucket: 'locate-507c2.appspot.com',
    iosClientId: '834378788334-1iia67o0clgl3af5d61l2v3fas31auvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.locateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZFvoTJX1npVRcpY36IQPxejH7lwWcQK4',
    appId: '1:834378788334:ios:399bf4e88b457101ddb2ff',
    messagingSenderId: '834378788334',
    projectId: 'locate-507c2',
    storageBucket: 'locate-507c2.appspot.com',
    iosClientId: '834378788334-1iia67o0clgl3af5d61l2v3fas31auvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.locateApp',
  );
}
